import test from 'node:test';
import assert from 'node:assert/strict';
import {access,readFile} from 'node:fs/promises';
import {ALL_STOPS,STOPS,getStop,canMove,readProgress,findPath} from '../src/journey.js';
import {PROJECTS} from '../src/projects.js';
import {metroArrivalFrame} from '../src/metro.js';
import {World} from '../src/world.js';

// Geometry tests do not require a GPU. Canvas calls generate text/texture data only.
globalThis.innerWidth=1440;globalThis.innerHeight=900;globalThis.matchMedia=()=>({matches:false});
const context={fillRect(){},strokeRect(){},fillText(){}};
globalThis.document={createElement:()=>({width:0,height:0,getContext:()=>context}),createElementNS:()=>({addEventListener(){},removeEventListener(){},set src(v){this.url=v;}})};

test('main route preserves the requested sequence and terminates at the yacht',()=>{let stop=STOPS[0],route=[];while(stop){assert.ok(!route.includes(stop.id),'no transit cycles');route.push(stop.id);stop=stop.next?getStop(stop.next):null;}assert.deepEqual(route,['shanghai','pudong','berkeley','oakland','sanfrancisco','redwood','stockholm','croatia']);assert.equal(getStop('shanghai').mode,'metro');assert.equal(getStop('sanfrancisco').mode,'caltrain');});
test('every original project has exactly one explorable location and valid local artwork',async()=>{assert.equal(PROJECTS.length,18);for(const p of PROJECTS){assert.equal(ALL_STOPS.filter(s=>s.projects.includes(p.id)).length,1,p.id);assert.ok(p.img.startsWith('./images/'),p.id);const data=await readFile(new URL('../'+p.img,import.meta.url));assert.ok(data.length>1000,`${p.id} is an actual image, not an error document`);assert.ok(!(data.toString('utf8',0,50).includes('<html')),p.id);}});
test('all 17 chapters construct with reachable project exhibits and boarding points',()=>{const w=new World(null);for(const stop of ALL_STOPS){w.load(stop,stop.projects.map(id=>PROJECTS.find(p=>p.id===id)));assert.ok(w.root.children.length>0,stop.id);assert.ok(canMove(...stop.spawn,w.colliders,w.bounds),`${stop.id} spawn is free`);assert.equal(w.markers.filter(m=>m.kind==='project').length,stop.id==='shanghai'?0:stop.projects.length);for(const m of w.markers){assert.ok(canMove(m.x,m.z+2,w.colliders,w.bounds),`${stop.id}/${m.kind} approach is reachable`);}if(stop.next){const gate=w.markers.find(m=>m.kind==='gate'||m.kind==='entrance');for(let z=stop.spawn[1];z>=gate.z+2;z-=.2)assert.ok(canMove(0,z,w.colliders,w.bounds),`${stop.id} guidance corridor at ${z}`);}assert.ok(w.root.children.some(c=>c.isInstancedMesh),`${stop.id} batches geometry`);}w.clear();});
test('each transit mode constructs and releases resources across repeated journeys',()=>{const w=new World(null);w.load(STOPS[0],[]);for(let i=0;i<2;i++)for(const mode of ['metro','flight','bart','caltrain']){w.startTransit(mode);assert.ok(w.root.children.length>0);w.clear();assert.equal(w.root.children.length,0);}});
test('collision blocks walls and world edges while permitting sliding',()=>{const walls=[[2,4,-2,2]],bounds=[-10,10,-10,10];assert.equal(canMove(3,0,walls,bounds),false);assert.equal(canMove(10,0,walls,bounds),false);assert.equal(canMove(1,3,walls,bounds),true);});
test('corrupt or unavailable saved progress cannot break the journey',()=>{assert.deepEqual(readProgress({getItem:()=>'{broken'}),{visited:[],discovered:[]});assert.deepEqual(readProgress({getItem:()=>{throw Error('denied');}}),{visited:[],discovered:[]});assert.deepEqual(readProgress({getItem:()=>JSON.stringify({visited:['shanghai','unknown'],discovered:5})}),{visited:['shanghai'],discovered:[]});});
test('all browser module imports resolve locally without a CDN',async()=>{const seen=new Set();async function walk(path){if(seen.has(path))return;seen.add(path);const s=await readFile(new URL(path),'utf8');for(const match of s.matchAll(/from\s+['"]([^'"]+)['"]/g)){assert.ok(match[1].startsWith('.'),`local module ${match[1]}`);const resolved=new URL(match[1],path);await access(resolved);await walk(resolved.href);}}await walk(new URL('../script.js',import.meta.url).href);});

test("guidance routes around obstacles instead of walking into them",()=>{const walls=[[-1,1,-3,3]];const path=findPath([-5,0],[5,0],walls,[-10,10,-10,10]);assert.ok(path?.length);for(const [x,z]of path)assert.ok(canMove(x,z,walls,[-10,10,-10,10]));assert.ok(path.some(p=>Math.abs(p[1])>3));});

test('all interface colors are strictly achromatic',async()=>{const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');for(const match of css.matchAll(/#([0-9a-f]{3,8})\b/gi)){const c=match[1];const rgb=c.length<=4?c.slice(0,3).split(''):c.slice(0,6).match(/../g);assert.equal(new Set(rgb).size,1,`colored UI token #${c}`);}});
test('decluttered interface retains all controller targets and removes the persistent panels',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),code=await readFile(new URL('../script.js',import.meta.url),'utf8');const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const [,id]of code.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(id),`missing UI element ${id}`);for(const id of ['welcome','minimap','chapter-number','quest-detail','coordinates'])assert.ok(!ids.has(id),`${id} removed`);assert.ok(ids.has('menu-button'));});
test('physical material assets and the HDR environment are present',async()=>{for(const file of ['morning.hdr','paving-color.jpg','paving-normal.jpg','paving-roughness.jpg','paving-ao.jpg']){const data=await readFile(new URL('../images/pbr/'+file,import.meta.url));assert.ok(data.length>10000,file);if(file.endsWith('hdr'))assert.ok(data.toString('ascii',0,100).includes('RADIANCE'));else assert.equal(data.readUInt16BE(0),0xffd8);}});


test('Bund landmarks have finite geometry, preserved materials and reachable walking routes',()=>{
 const w=new World(null);w.load(STOPS[0],[PROJECTS.find(p=>p.id==='nodeobjects')]);
 for(const name of ['Swatch Art Peace Hotel','Customs House','Former HSBC Building','Fairmont Peace Hotel','Shanghai Tower','Shanghai World Financial Center','Jin Mao Tower','Oriental Pearl Tower'])assert.ok(w.landmarks.includes(name),name);
 let instances=0;w.root.traverse(o=>{if(o.isInstancedMesh){instances+=o.count;for(const value of o.instanceMatrix.array)assert.ok(Number.isFinite(value),'finite transform');assert.ok(o.material,'valid material');}if(o.geometry){const pos=o.geometry.getAttribute('position');for(const value of pos.array)assert.ok(Number.isFinite(value),'finite vertex');}});assert.ok(instances>1000);
 for(const marker of w.markers){const path=findPath(STOPS[0].spawn,[marker.x,marker.z+2],w.colliders,w.bounds);assert.ok(path?.length,marker.kind+' is reachable from waterfront');}
 const brick=w.mat('bund-brick'),map=brick.map;let disposed=false;map.addEventListener('dispose',()=>disposed=true);w.load(STOPS[1],[]);assert.equal(disposed,false,'shared architectural textures survive travel');w.load(STOPS[0],[]);assert.equal(w.mat('bund-brick').map,map);assert.ok(w.puddles.isReflector);w.clear();assert.equal(w.puddles,null);
});
test('new Bund materials are local JPEGs with recorded CC0 sources',async()=>{const manifest=JSON.parse(await readFile(new URL('../images/pbr/bund-sources.json',import.meta.url),'utf8'));for(const item of manifest){assert.equal(item.license,'CC0-1.0');const bytes=await readFile(new URL('../'+item.path,import.meta.url));assert.equal(bytes.readUInt16BE(0),0xffd8);assert.ok(bytes.length>10000);}});


test('Shanghai exploration stays inside visible garden edges and keeps golden lighting local',()=>{
 const w=new World(null);w.load(STOPS[0],[]);
 for(const [x,z]of [[0,85],[0,-49],[-12.1,0],[17,0]])assert.equal(canMove(x,z,w.colliders,w.bounds),false,`edge ${x},${z}`);
 assert.equal(w.goldenSky.visible,true);assert.equal(w.clouds.visible,false);assert.ok(w.sunOffset.y/w.sunOffset.length()<.2,'low sun');
 assert.ok(w.water.material.uniforms.sunDirection.value.distanceTo(w.sunOffset.clone().normalize())<.001,'water highlights align with the sun');
 w.load(STOPS[1],[]);assert.equal(w.goldenSky.visible,false,'airport retains daylight');assert.equal(w.sun.intensity,2.7);
 w.load(STOPS[0],[]);assert.equal(w.goldenSky.visible,true);w.clear();
});
test('project presentation contains no inferred launch status or generic portfolio paragraph',async()=>{
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),code=await readFile(new URL('../script.js',import.meta.url),'utf8');
 for(const phrase of ['This project has not launched','Part of Qianhua','IN DEVELOPMENT','LAUNCHED PROJECT','project-status','project-copy'])assert.ok(!(html+code).includes(phrase),phrase);
});

test('main cities use distinct environments and inland destinations have no river',()=>{const w=new World(null),seen=new Set();for(const id of ['berkeley','oakland','redwood','sanfrancisco','stockholm']){const stop=getStop(id);w.load(stop,stop.projects.map(id=>PROJECTS.find(p=>p.id===id)));assert.ok(!seen.has(w.sceneKind),id);seen.add(w.sceneKind);if(['berkeley','oakland','redwood'].includes(id))assert.equal(w.water,null,id+' is inland');for(const m of w.markers)assert.ok(findPath(stop.spawn,[m.x,m.z+2],w.colliders,w.bounds)?.length,id+' '+m.kind);}w.clear();});
test('projects are integrated into booths and an explorable metro concourse',()=>{const w=new World(null),sh=getStop('shanghai');w.load(sh,[PROJECTS.find(p=>p.id==='nodeobjects')]);assert.ok(w.markers.some(m=>m.kind==='entrance'));assert.ok(!w.markers.some(m=>m.kind==='project'));w.loadMetro(sh,[PROJECTS.find(p=>p.id==='nodeobjects')]);assert.equal(w.zone,'metro');assert.equal(w.goldenSky.visible,false);const ad=w.markers.find(m=>m.kind==='project');assert.equal(ad.presentation,'wall-lightbox');assert.ok(ad.y>1.5,'advertisement is at eye level');assert.ok(canMove(0,8,w.colliders,w.bounds),'center aisle is clear');assert.ok(findPath([0,17],ad.approach,w.colliders,w.bounds)?.length,'wall ad is reachable');assert.ok(w.puddles.isReflector,'interior floor reflects actual architecture');for(const m of w.markers)assert.ok(findPath([0,15],[m.x,m.z+2],w.colliders,w.bounds)?.length,m.kind);w.load(getStop('berkeley'),['markitai','mundus'].map(id=>PROJECTS.find(p=>p.id===id)));assert.equal(w.zone,null);assert.ok(w.markers.filter(m=>m.kind==='project').every(m=>m.presentation==='campus-booth'));assert.ok(w.landmarks.includes('Campanile'));assert.ok(w.landmarks.includes('Doe Library'));w.clear();});

test('metro waits, arrives, opens its doors, and resets between visits',()=>{const w=new World(null);w.loadMetro(getStop('shanghai'),[]);w.update(1,1);assert.equal(w.metroArrival.phase,'waiting');w.camera.position.z=-10;for(let i=0;i<11;i++)w.update(i,1);assert.equal(w.metroArrival.phase,'boarding');assert.equal(w.metroArrival.train.position.x,0);assert.equal(metroArrivalFrame(0).doors,0);assert.equal(metroArrivalFrame(7).doors,0);assert.equal(metroArrivalFrame(11).doors,1);assert.equal(metroArrivalFrame(0,true).phase,'boarding');w.startTransit('metro');assert.equal(w.metroArrival,null);assert.equal(w.zone,'train');assert.ok(w.trainRide.doors.length>0);w.arriveMetro();w.update(30,2);assert.equal(w.trainRide.platform.visible,true);assert.equal(w.trainRide.tunnel.visible,false);assert.ok(w.trainRide.doors.every(d=>Math.abs(d.mesh.position.z-d.home)>.6));w.load(getStop('pudong'),[]);assert.equal(w.trainRide,null);assert.equal(w.zone,null);assert.equal(w.sceneKind,'airport-terminal');});

test('Bay Area district geometry stays finite and preserves the main walking routes',()=>{const w=new World(null);for(const id of ['berkeley','sanfrancisco','oakland','redwood']){const stop=getStop(id);w.load(stop,[]);w.root.traverse(o=>{if(o.geometry)for(const v of o.geometry.attributes.position.array)assert.ok(Number.isFinite(v),id+' finite geometry');if(o.isInstancedMesh)for(const v of o.instanceMatrix.array)assert.ok(Number.isFinite(v),id+' finite transform');});assert.ok(findPath(stop.spawn,[0,-28],w.colliders,w.bounds)?.length,id+' route');if(id==='sanfrancisco')for(const name of ['Salesforce Tower','Transamerica Pyramid'])assert.ok(w.landmarks.includes(name),name);}w.clear();});
