export const concepts = [
  {
    id: "geography",
    n: "01",
    x: 310,
    y: 48,
    title: "scattered ports",
    sub: "GEOGRAPHY",
    body: "Ports, islands and highlands across an enormous ocean. Knowledge, capital and opportunity appear to be elsewhere. Mobility is the founding advantage; belonging is the unresolved question.",
  },
  {
    id: "worldview",
    n: "02",
    x: 310,
    y: 145,
    title: "a set of coordinates",
    sub: "WORLDVIEW",
    body: "The world is read through routes rather than homelands. Ships matter more than houses, maps more than territory. Leaving becomes a course correction. Arriving is harder to understand.",
  },
  {
    id: "method",
    n: "03",
    x: 310,
    y: 246,
    title: "perception under uncertainty",
    sub: "CORE CAPABILITY",
    body: "Observe quickly. Find the variables that matter. Model an unfamiliar system, then act. Wind, markets and technological change belong to the same family of problems: systems one must learn to read.",
  },
  {
    id: "power",
    n: "04",
    x: 104,
    y: 365,
    title: "competence",
    sub: "GOVERNMENT",
    body: "A technocratic maritime republic. Authority follows judgment, information and execution. Fleets, laboratories and trading houses become centers of power. Its danger: confusing the ability to solve a problem with the moral right to decide which problems matter.",
  },
  {
    id: "economy",
    n: "05",
    x: 310,
    y: 365,
    title: "compress complexity",
    sub: "ECONOMY",
    body: "Find the five variables inside the hundred. Software, finance, AI, design and trade turn unstructured complexity into useful systems. Disruption rewards its strongest industry: rapid modeling under uncertainty.",
  },
  {
    id: "education",
    n: "06",
    x: 516,
    y: 365,
    title: "enter the unknown",
    sub: "EDUCATION",
    body: "Languages, mathematics, history, navigation, engineering and rhetoric; then a laboratory, a foreign city, a company or a ship. The examination: no one is going to tell you what to do. What do you do? Adaptability flourishes; purpose remains difficult.",
  },
  {
    id: "love",
    n: "07",
    x: 104,
    y: 486,
    title: "altered course",
    sub: "LOVE",
    body: "Two independent trajectories choose to deviate for one another. “I changed course to find you.” Autonomy makes the choice beautiful and the intersection rare. Its literature is full of missed encounters.",
  },
  {
    id: "art",
    n: "08",
    x: 310,
    y: 486,
    title: "small human signals",
    sub: "AESTHETICS",
    body: "Black water. One warm light. A mast dividing the Milky Way. Negative space lets the universe remain visible. Poems are short; architecture is spacious. If the image is true, it can remain larger than its explanation.",
  },
  {
    id: "belief",
    n: "09",
    x: 516,
    y: 486,
    title: "learn to see",
    sub: "BELIEF",
    body: "Disciplined attention becomes a form of prayer. Success gradually turns accurate perception into an expectation of protection. A late dispute asks what understanding another person obliges us to do for them.",
  },
  {
    id: "conflict",
    n: "10",
    x: 155,
    y: 625,
    title: "speed is not depth",
    sub: "CLASS & CONTEXT",
    body: "A high-context elite compresses its reasoning until institutions can no longer read it. Procedure feels slow; speed feels arrogant. People who rapidly redesign systems become visible while those who patiently maintain them disappear.",
  },
  {
    id: "apex",
    n: "11",
    x: 465,
    y: 625,
    title: "intelligence as certainty",
    sub: "THE APEX",
    body: "Worldwide ports, research institutes and schools institutionalize its adaptability. Success hardens into a dangerous conviction: there is no problem sufficient intelligence cannot solve. Competence begins to resemble control.",
  },
  {
    id: "question",
    n: "12",
    x: 310,
    y: 754,
    title: "where to remain",
    sub: "DECLINE",
    body: "The ports remain prosperous while commitments grow shorter. A civilization adept at comparing possible lives struggles to sustain work whose benefits belong to an unborn generation. Its final inscription asks where to remain.",
  },
];
export const relations = [
  ["geography", "worldview"],
  ["worldview", "method"],
  ["method", "power"],
  ["method", "economy"],
  ["method", "education"],
  ["worldview", "love"],
  ["method", "art"],
  ["method", "belief"],
  ["power", "conflict"],
  ["education", "conflict"],
  ["economy", "apex"],
  ["belief", "apex"],
  ["conflict", "question"],
  ["apex", "question"],
];
export const facets = {
  geography: [
    "ports",
    "islands",
    "highlands",
    "knowledge",
    "capital",
    "opportunity",
    "currents and seasons",
    "somewhere else",
  ],
  worldview: [
    "homeland",
    "coordinates",
    "ships",
    "houses",
    "maps",
    "territory",
    "leaving",
    "arrive",
  ],
  method: [
    "judgment",
    "information",
    "execute",
    "rapid modeling",
    "uncertainty",
    "adaptability",
    "technological disruption",
    "chaos",
  ],
  power: [
    "maritime republic",
    "authority",
    "competence",
    "fleets",
    "laboratories",
    "trading houses",
    "context is power",
    "moral legitimacy",
  ],
  economy: [
    "complexity",
    "five",
    "software",
    "finance",
    "ai",
    "design",
    "international trade",
    "structure",
  ],
  education: [
    "languages",
    "mathematics",
    "history",
    "navigation",
    "engineering",
    "rhetoric",
    "unfamiliar systems",
    "what do you do?",
  ],
  love: [
    "altered course",
    "autonomous trajectories",
    "voluntarily deviating",
    "independent",
    "singular exception",
    "intersection",
    "missed encounters",
    "changed course",
  ],
  art: [
    "negative space",
    "warm light",
    "black water",
    "bioluminescence",
    "milky way",
    "human figure",
    "poems",
    "explanation",
  ],
  belief: [
    "wind",
    "stars",
    "markets",
    "accuracy",
    "prayer",
    "humility",
    "grief",
    "what do you owe",
  ],
  conflict: [
    "high context",
    "low context",
    "procedure",
    "consensus",
    "speed",
    "depth",
    "redesign",
    "maintain",
  ],
  apex: [
    "ports across the world",
    "research institutes",
    "schools",
    "technologies",
    "generations",
    "unstoppable",
    "sufficient intelligence",
    "decline",
  ],
  question: [
    "attachment",
    "alternatives",
    "possible lives",
    "patient effort",
    "ability to leave",
    "unborn generation",
    "accounts of travel",
    "where to remain",
  ],
};
export const imagesByConcept = {
  geography: ["canon-1908", "before-departure", "leaving-land", "canon-1863"],
  worldview: ["small-boat", "land-at-last", "evening-sail", "the-wake"],
  method: ["learning-the-boat", "boat-signals", "cabin", "wind-made-visible"],
  power: ["canon-1861", "canon-1857", "under-sail", "galley"],
  economy: ["wind-made-visible", "canon-1886", "canon-1887", "blue-water"],
  education: ["cabin", "boat-signals", "morning-deck", "learning-the-boat"],
  love: [
    "off-watch-portrait",
    "rum-for-the-ocean",
    "human-signal",
    "altered-course",
  ],
  art: ["stardust", "harvest-moon", "pink-water", "red-horizon"],
  belief: ["rainbow", "two-rainbows", "stardust", "quiet-morning"],
  conflict: ["weather", "sea-legs", "galley", "on-watch"],
  apex: ["small-boat", "canon-2041", "evening-sail", "under-sail"],
  question: ["land-at-last", "first-shower", "the-wake", "harvest-moon"],
};
