export const dayMedia = {
  12: [
    {
      day: 12,
      file: "canon-2041",
      caption: "atalanta",
      alt: "The name Atalanta painted on the boat’s hull",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 12,
      file: "canon-1846",
      caption: "the small world below deck",
      alt: "A person sitting inside the sailboat cabin",
      label: "PHOTOGRAPH",
      width: 1200,
      height: 1800,
    },
    {
      day: 12,
      file: "canon-1854",
      caption: "before the horizon takes over",
      alt: "A crew member resting in the sunlit cockpit",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 12,
      file: "canon-1863",
      caption: "water, already everywhere",
      alt: "Deep blue water beside the bow",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 12,
      file: "canon-1886",
      caption: "an arrangement with the wind",
      alt: "A white sail overhead against the blue sky",
      label: "PHOTOGRAPH",
      width: 1200,
      height: 1800,
    },
    {
      day: 12,
      file: "canon-1887",
      caption: "outward",
      alt: "The boom and lines framing the open sea",
      label: "PHOTOGRAPH",
      width: 1200,
      height: 1800,
    },
    {
      day: 12,
      file: "canon-1861",
      caption: "a world the width of a boat",
      alt: "Crew members seen beneath the boom",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 12,
      file: "canon-1857",
      caption: "leaving room for the sea",
      alt: "The sailboat deck against a wide horizon",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 12,
      file: "before-departure",
      caption: "the last evening in harbor",
      alt: "An orange sky over the marina, framed by the sailboat cockpit",
      label: "PHOTOGRAPH",
      width: 1350,
      height: 1800,
    },
  ],
  13: [
    {
      day: 13,
      file: "canon-1908",
      caption: "the last green on the horizon",
      alt: "Green Hawaiian mountains behind the boat’s boom and rigging",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
    },
    {
      day: 13,
      file: "leaving-hawaii",
      caption: "the island getting smaller",
      alt: "Green Hawaiian coastline passing beyond the boat’s rigging",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 13,
      file: "blue-water",
      caption: "a new scale of blue",
      alt: "Crew working on deck under a white sail in bright blue water",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 406,
      height: 720,
    },
    {
      day: 13,
      file: "under-sail",
      caption: "wind in the sails",
      alt: "Crew at the helm as the sailboat heels into the sea",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 13,
      file: "leaving-land",
      caption: "the last shape of land",
      alt: "Green Hawaiian coastline beyond the boat’s rigging",
      video: false,
      label: "PHOTOGRAPH",
    },
  ],
  14: [
    {
      day: 14,
      file: "stardust",
      caption: "light already gone",
      alt: "The Milky Way across a dense field of stars",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1200,
      coverPosition: "50% 0%",
      cropSky: true,
    },
    {
      day: 14,
      file: "rainbow",
      caption: "a brief interruption of light",
      alt: "A rainbow over the open ocean beyond the boat’s stern",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 8,
      width: 1280,
      height: 720,
    },
    {
      day: 14,
      file: "evening-sail",
      caption: "the sky, still going",
      alt: "White sail against blue evening sky and rolling ocean",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 1280,
      height: 720,
    },
  ],
  15: [
    {
      day: 15,
      file: "dawn-beyond-the-rigging",
      caption: "the first light beyond the rigging",
      alt: "An orange dawn along the ocean horizon, framed by the boat’s dark rigging",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 14,
      width: 1280,
      height: 720,
    },
    {
      day: 15,
      file: "off-watch-portrait",
      caption: "off watch",
      alt: "Qianhua resting at the cabin table in warm sunlight",
      label: "PHOTOGRAPH",
      width: 1800,
      height: 1046,
    },
    {
      day: 15,
      file: "cabin",
      caption: "between watches",
      alt: "Sunlight falling into the wood-lined cabin beneath navigation instruments",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 1280,
      height: 720,
    },
    {
      day: 15,
      file: "off-watch-motion",
      caption: "morning, at an angle",
      alt: "Warm morning light on the sail and tilted deck",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 10,
      width: 406,
      height: 720,
    },
    {
      day: 15,
      file: "galley",
      caption: "a moving kitchen",
      alt: "A crew member cooking in the galley while the boat moves",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 15,
      file: "dolphins-phone-0608",
      caption: "company beyond the rail",
      alt: "A phone view over the sailboat rail toward the passing sea",
      video: true,
      label: "MOVING IMAGE",
      width: 406,
      height: 720,
      durationSeconds: 10.73,
    },
  ],
  16: [
    {
      day: 16,
      file: "weather",
      caption: "the sea raining back upward",
      alt: "Waves breaking alongside the heeled sailboat",
      video: true,
      label: "MOVING IMAGE",
    },
    {
      day: 16,
      file: "sea-legs",
      caption: "the body keeps the log",
      alt: "Bruised legs resting in the cockpit while water churns behind the boat",
      label: "PHOTOGRAPH",
      width: 1350,
      height: 1800,
    },
    {
      day: 16,
      file: "weather-from-the-cockpit",
      caption: "everything at an angle",
      alt: "A phone view of the tilted deck and white waves in rough water",
      label: "MOVING IMAGE",
      video: true,
      width: 406,
      height: 720,
      durationSeconds: 9,
    },
    {
      day: 16,
      file: "storm-phone-0607",
      caption: "weather across the stern",
      alt: "Rough seas and spray behind the cockpit winches",
      video: true,
      label: "MOVING IMAGE",
      width: 1280,
      height: 720,
      durationSeconds: 16,
    },
  ],
  17: [],
  18: [
    {
      day: 18,
      file: "pink-water",
      caption: "the water borrowing the sky",
      alt: "Pink light shimmering across waves beside the deck",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 18,
      file: "pink-horizon",
      caption: "nothing between sea and sky",
      alt: "A rose-colored sky beyond the sail and the ocean horizon",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 18,
      file: "quiet-morning",
      caption: "the wind went quiet",
      alt: "A crew member on deck in soft morning light over a calm sea",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 18,
      file: "rainbow-at-sea",
      caption: "a color with nowhere to land",
      alt: "A rainbow descending from a cloud into the open ocean",
      label: "MOVING IMAGE",
      video: true,
      width: 406,
      height: 720,
      durationSeconds: 9,
    },
    {
      day: 18,
      file: "still-water",
      caption: "when the wind disappeared",
      alt: "Soft dawn light over nearly still ocean water",
      video: true,
      label: "MOVING IMAGE",
    },
  ],
  19: [
    {
      day: 19,
      file: "small-boat",
      caption: "a small human signal",
      alt: "A drone view of a lone sailboat crossing an immense blue ocean",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 14,
      width: 1280,
      height: 720,
    },
    {
      day: 19,
      file: "stern-under-sail",
      caption: "onward, from astern",
      alt: "A drone follows the sailboat from behind as it sails forward across the blue Pacific",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 14,
      width: 1280,
      height: 720,
    },
    {
      day: 19,
      file: "up-the-mast",
      caption: "a different view of the problem",
      alt: "A crew member suspended beside the mast and white sail, high above the deck",
      label: "MOVING IMAGE",
      video: true,
      width: 1280,
      height: 720,
      durationSeconds: 10,
    },
  ],
  20: [
    {
      day: 20,
      file: "rum-for-the-ocean",
      caption: "a little rum for the ocean",
      alt: "Crew sharing a drink and pouring an offering over the side at dusk",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 13,
      width: 1280,
      height: 720,
    },
    {
      day: 20,
      file: "wind-made-visible",
      caption: "the wind made visible",
      alt: "A white and blue spinnaker filling overhead against the sky",
      label: "MOVING IMAGE",
      video: true,
      width: 1280,
      height: 720,
      durationSeconds: 10,
    },
  ],
  21: [
    {
      day: 21,
      file: "morning-deck",
      caption: "before the day begins",
      alt: "The sailboat’s bow and white sail over calm water in early light",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 1280,
      height: 720,
    },
    {
      day: 21,
      file: "golden-horizon",
      caption: "gold across the water",
      alt: "Golden sunlight on the horizon beside the sail and deck, with waves breaking along the hull",
      video: true,
      label: "MOVING IMAGE",
      durationSeconds: 10,
      width: 1280,
      height: 720,
    },
  ],
  22: [
    {
      day: 22,
      file: "learning-the-boat",
      caption: "learning to listen",
      alt: "A low-angle portrait beside the sail and rigging",
      label: "PHOTOGRAPH",
      width: 1206,
      height: 678,
    },
    {
      day: 22,
      file: "boat-signals",
      caption: "the boat speaks",
      alt: "Sunlight through clouds above the cockpit and moving waves",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
  ],
  23: [
    {
      day: 23,
      file: "rainbow-watch",
      caption: "another kind of weather",
      alt: "A rainbow behind the helmsman under a pink-blue sky",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 1280,
      height: 720,
    },
    {
      day: 23,
      file: "on-watch",
      caption: "the human figure, small enough",
      alt: "A person on deck beneath sails and a cloudy sky",
      video: false,
      label: "PHOTOGRAPH",
    },
    {
      day: 23,
      file: "red-horizon",
      caption: "a seam of red in the dark",
      alt: "A narrow red dawn on the horizon behind dark rigging",
      label: "MOVING IMAGE",
      video: true,
      width: 406,
      height: 720,
      durationSeconds: 9,
    },
  ],
  24: [
    {
      day: 24,
      file: "altered-course",
      caption: "on her own terms",
      alt: "Aerial view of the sailboat and its wake in warm light",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 2.15,
      width: 1280,
      height: 720,
    },
    {
      day: 24,
      file: "sail-and-swell",
      caption: "listening to the sail",
      alt: "A phone view along the heeling deck, with the white sail pulling above rolling waves",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 406,
      height: 720,
    },
  ],
  25: [
    {
      day: 25,
      file: "the-wake",
      caption: "not one asking to be carried",
      alt: "White wake dissolving into intensely blue water",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 9,
      width: 1280,
      height: 720,
    },
    {
      day: 25,
      file: "gold-in-the-wake",
      caption: "a little gold, left behind",
      alt: "A phone video moving from waves beside the deck to golden sunlight on the ocean horizon",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 13,
      width: 406,
      height: 720,
    },
  ],
  26: [
    {
      day: 26,
      file: "harvest-moon",
      caption: "a light on the other side",
      alt: "An orange moon rising above dark waves and a pink sky",
      label: "PHOTOGRAPH",
      width: 1350,
      height: 1800,
      coverPosition: "50% 65%",
    },
    {
      day: 26,
      file: "human-signal",
      caption: "someone else’s watch",
      alt: "A person standing on deck against a vast pink and blue horizon",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 11,
      width: 1280,
      height: 720,
    },
    {
      day: 26,
      file: "distant-freighter",
      caption: "a small signal on the horizon",
      alt: "A freighter passing far away beneath a pink evening sky",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 406,
      height: 720,
    },
    {
      day: 26,
      file: "moon-water",
      caption: "the long blue distance",
      alt: "Gentle ocean waves under a pale pink sky",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 12,
      width: 406,
      height: 720,
    },
  ],
  27: [
    {
      day: 27,
      file: "first-sun-on-watch",
      caption: "the sun finds the sails",
      alt: "Low golden sunlight across the ocean beside the sailboat’s sails and rigging",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 10,
      width: 1280,
      height: 720,
    },
    {
      day: 27,
      file: "watch-in-golden-light",
      caption: "the hours we keep together",
      alt: "Crew gathered around the cockpit and helm in warm low sunlight",
      label: "MOVING IMAGE",
      video: true,
      durationSeconds: 13,
      width: 1280,
      height: 720,
    },
    {
      day: 27,
      file: "two-rainbows",
      caption: "the sky, twice",
      alt: "A double rainbow beyond the boat’s canopy and rigging",
      label: "MOVING IMAGE",
      video: true,
      width: 406,
      height: 720,
      durationSeconds: 10,
    },
  ],
  28: [],
  29: [
    {
      day: 29,
      file: "land-at-last",
      caption: "finally, land",
      alt: "Shore lights reflected across the dark water as the boat approaches land",
      label: "PHOTOGRAPH",
      width: 1350,
      height: 1800,
      coverPosition: "50% 45%",
    },
    {
      day: 29,
      file: "first-shower",
      caption: "finally, a shower",
      alt: "A mirror portrait in a red top after returning ashore",
      label: "PHOTOGRAPH",
      width: 1350,
      height: 1800,
    },
  ],
};

export const shoreMedia = [
  {
    file: "the-familiar-again",
    caption: "the familiar, again",
    alt: "Qianhua overlooking the Golden Gate Bridge and San Francisco Bay in the evening light",
    label: "MOVING IMAGE",
    video: true,
    muted: true,
    durationSeconds: 10.917,
    width: 1280,
    height: 720,
  },
];
